#!/bin/bash

#[ Script ]--------------------------------------------------------------------#
#                                                                              #
# dbdump                                                                       #
#                                                                              #
# PT-br:                                                                       #
# Script  para  efetuar backup de bancos de dados MySQL e fazer purga de dados #
# antigos.                                                                     #
#                                                                              #
# ----------------------------                                                 #
#                                                                              #
# EN:                                                                          #
# Backup and purge script for MySQL.                                           #
#                                                                              #
# reimlima@gmail.com                                                           #
# $Id: dbdump,v 2.3 2015/05/15 reimlima Exp reimlima $                         #
#                                                                              #
#[ License ]-------------------------------------------------------------------#
#                                                                              #
# Copyright (c) 2015 Reinaldo Marques de Lima reimlima@gmail.com               #
#                                                                              #
# PT-br:                                                                       #
# A permissão  é  concedida,  a título gratuito, a qualquer pessoa que obtenha #
# uma   cópia   deste   software   e   arquivos   de  documentação  associados #
# (o "Software"),  para  lidar  com  o  Software sem restrição, incluindo, sem #
# limitação,  os  direitos  de  usar,  copiar,  modificar,  mesclar, publicar, #
# distribuir,  sublicenciar,  e / ou vender cópias do Software, e permitir que #
# as  pessoas  a  quem  o  Software  é fornecido o façam, sujeito às seguintes #
# condições:                                                                   #
#                                                                              #
# O  aviso de copyright acima e este aviso de permissão devem ser incluídos em #
# todas as cópias ou partes substanciais do Software.                          #
#                                                                              #
# O  SOFTWARE É FORNECIDO "COMO ESTÁ", SEM GARANTIA DE QUALQUER TIPO, EXPRESSA #
# OU  IMPLÍCITA,  INCLUINDO,  SEM  LIMITAÇÃO, AS GARANTIAS DE COMERCIALIZAÇÃO, #
# ADEQUAÇÃO  A  UM  DETERMINADO  FIM E NÃO VIOLAÇÃO. EM NENHUM CASO OS AUTORES #
# OU  DIREITOS  AUTORAIS  TITULARES  SER  RESPONSÁVEL POR QUALQUER RECLAMAÇÃO, #
# DANOS  OU  OUTRAS  RESPONSABILIDADES,  SEJA  EM  UMA  AÇÃO DE CUMPRIMENTO DE #
# CONTRATO OU DE OUTRA FORMA, DECORRENTE DE, OU EM CONEXÃO COM O SOFTWARE OU O #
# USO OU OUTRAS FUNÇÕES DO SOFTWARE.                                           #
#                                                                              #
# Exceto  conforme  contido no presente aviso, o nome do (s) dos detentores de #
# direitos  autorais acima não devem ser utilizados em publicidade ou de outra #
# forma  para  promover  a venda, uso ou outras negociações deste Software sem #
# autorização prévia por escrito.                                              #
#                                                                              #
# ----------------------------                                                 #
#                                                                              #
# EN:                                                                          #
# Permission is hereby granted, free of charge, to any person obtaining a copy #
# of  this  software  and  associated  documentation  files  (the "Software"), #
# to  deal  in  the Software without restriction, including without limitation #
# the  rights  to  use,  copy, modify, merge, publish, distribute, sublicense, #
# and/or  sell  copies  of  the  Software,  and  to permit persons to whom the #
# Software is furnished to do so, subject to the following conditions:         #
#                                                                              #
# The  above  copyright notice and this permission notice shall be included in #
# all copies or substantial portions of the Software.                          #
#                                                                              #
# THE  SOFTWARE  IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR #
# IMPLIED,  INCLUDING  BUT  NOT  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, #
# FITNESS  FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE #
# AUTHORS  OR  COPYRIGHT  HOLDERS  BE  LIABLE  FOR ANY CLAIM, DAMAGES OR OTHER #
# LIABILITY,   WHETHER   IN   AN   ACTION  OF  CONTRACT,  TORT  OR  OTHERWISE, #
# ARISING FROM,  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER #
# DEALINGS IN THE SOFTWARE.                                                    #
#                                                                              #
# Except  as  contained  in  this  notice,  the name(s) of the above copyright #
# holders  shall  not be used in advertising or otherwise to promote the sale, #
# use or other dealings in this Software without prior written authorization.  #
#                                                                              #
#[ Changelog ]-----------------------------------------------------------------#
#                                                                              #
# v1   - [02/20/2015] - First release. Only shows informations                 #
# v2   - [02/23/2015] - Stable Version                                         #
# v2.1 - [02/24/2015] - Added "--single-transaction" parameter for "non lock"  #
#                       entire database.                                       #
# v2.2 - [02/26/2015] - Removed unnecessary lock file.                         #
#                     - Better comment about conf file.                        #
# v2.3 - [05/15/2015] - Added option to send dump file to a remote server via  #
#                       rsync.                                                 #
#                                                                              #
#------------------------------------------------------------------------------#

#[ Variables ]-----------------------------------------------------------------#

DEBUG=0
FIND=$(which find)
DATE=$(which date)
GZIP=$(which gzip)
SCRIPTNAME=$(basename $0)
MYSQLDUMP=$(which mysqldump)
DUMPDATE=$($DATE '+%Y%m%d%H%M')
LOCKFILE=/tmp/${SCRIPTNAME}.lock

# script conf file. Set here the full path like "/etc/dbddump/dbdump.conf"
SCRIPTCONFFILE="dbdump.conf"

#[ Functions ]-----------------------------------------------------------------#

trapfunction(){

	# Function called by 'trap' command. Only removes lock
	# file if the process PID was the same in the file.

	PIDOFMYSELF=$$
	PIDINLOCKFILE=$(cat $LOCKFILE)
	if [ "$PIDOFMYSELF" == "$PIDINLOCKFILE" ] ; then
		rm $LOCKFILE
	else
		echo
		echo "PID: $PIDINLOCKFILE"
		echo
	fi
	
}

trap trapfunction 0 1 2 3 9 15

exiterrorfunc(){

	# Generic output function, show the message given,
	# and then exits with the given code.

	# Parse message and exit code
	EXITCODE=$(echo $@ | awk '{print $NF}')
	EXITMESSAGE=$(echo $@ | awk '{ $NF = ""; print $0}')
	[ $DEBUG -eq 1 ] && echo $EXITMESSAGE
	echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - $EXITMESSAGE" >> $DBDUMPLOG
	exit $EXITCODE
	
}

dataDump(){
	
	# Execute database dump and then compress the created file
	# using options given in the dbdump.conf file
	
	if [[ $DBARRAY = "" ]] ; then
		DUMPINFO="Executing backup of All Databases"
		DBARRAY="--all-databases"
	else
		DUMPINFO="Executing backup of $DBARRAY Databases"
		DBARRAY="--databases $DBARRAY"
	fi
	echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - $DUMPINFO" >> $DBDUMPLOG
	[ $DEBUG -eq 1 ] && echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - $DUMPINFO"
	$MYSQLDUMP --single-transaction -u $DBUSER -p$DBPASSWORD $DBARRAY >> $DUMPPATH/$DUMPFILENAME.$DUMPDATE.sql
	wait
	$GZIP -9 $DUMPPATH/$DUMPFILENAME.$DUMPDATE.sql
	return
	
}

dataPurge(){
	
	# Automatic purge old files older than "DUMPRETENTION"
	# option in dbdump.conf
	
	echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - Removing files older than $DUMPRETENTION day" >> $DBDUMPLOG
	[ $DEBUG -eq 1 ] && echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - Removing files older than $DUMPRETENTION day"
	$FIND $DUMPPATH/ -type f -mtime +$DUMPRETENTION  -exec rm -vf {} \;
	return
	
}

sendBackupGzipFile(){

	# Send created dump file to a remote server via rsync

	BACKUPFULLNAME="$DUMPFILENAME.$DUMPDATE.sql.gz"
	echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - sendind the backup file \"$BACKUPFULLNAME\" to the remote host: $SERVERBKP" >> $DBDUMPLOG
	[ $DEBUG -eq 1 ] && echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - sendind the backup file \"$BACKUPFULLNAME\" to the remote host: $SERVERBKP"
	$RSYNC -tv $DUMPPATH/$BACKUPFULLNAME $SERVERBKPUSER@$SERVERBKP::$SERVERBKPPATH/ >> $DBDUMPLOG 2> /dev/null
	return

}

executionFlow(){
	
	# Makes the script orchestration
	
	dataPurge
	[ $? -eq 0 ] || exiterrorfunc "Something went wrong with Data Purge, check $DUMPPATH 1"
	wait
	dataDump
	[ $? -eq 0 ] || exiterrorfunc "Something went wrong with DB Dump, check $DUMPPATH 1"
	wait
	sendBackupGzipFile
	[ $? -eq 0 ] || exiterrorfunc "Something went wrong, check if the backup server is available 1"
	exiterrorfunc "All Operations were done successfully 0"
	
}

#[ Load conf file ]------------------------------------------------------------#

if [ -e $SCRIPTCONFFILE ] ; then
        source $SCRIPTCONFFILE
else
        exiterrorfunc "ERROR: $SCRIPTCONFFILE file not found 1"
fi

#[ tests, tests, tests ]-------------------------------------------------------#

# Validate if there is a lock file
if [ -e $LOCKFILE ]; then
        exiterrorfunc "There is another script running 1"
else
        echo "$$" > $LOCKFILE
fi

# Validate command line option
if [[ $1 = "" ]] ; then
	echo "--------------------------------------" >> $DBDUMPLOG
	executionFlow
elif [ `echo $1 | sed '/-d/!d'` ] ; then
	DEBUG=1
	echo "--------------------------------------" >> $DBDUMPLOG
	executionFlow
else
	exiterrorfunc "USAGE: Only use \"$SCRIPTNAME -d\" for debug 1"
fi
